### PR TITLE
chore: try no context switch

### PR DESCRIPTION
**Pull request by lucacasonato**

### CODE REVIEW

**Comment by lucacasonato** [comment]
It seems most of the time is spent on the `JSON.stringify` call.

**Comment by notfilippo** [comment]
This is ready to merge but I think we should close it in favour of keeping the `js_sys` until we develop a clean Typescript BSON encoder / decoder. 

Keeping js_sys will also be useful as rehydration of a BSON document could be done in Rust in the fashion as the encoding phase.

wdyt @lucacasonato ?

**Comment by lucacasonato** [comment]
SGTM. I like the simplicity of this, but indeed the rehydration might be easier to do in rust. Do you want to tackle that?

**Comment by notfilippo** [comment]
Sure! Will close this then.

**Pull request closed without merging**
